-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/TitleKey/db_patches/abstractSchemaChanges/patch-modify-tk_key.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/titlekey
  CHANGE tk_key tk_key VARBINARY(255) NOT NULL;
