-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TitleKey/db_patches//tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE titlekey (
  tk_page INT NOT NULL,
  tk_namespace INT NOT NULL,
  tk_key TEXT NOT NULL,
  PRIMARY KEY(tk_page)
);

CREATE INDEX name_key ON titlekey (tk_namespace, tk_key);
