-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TitleKey/db_patches//tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/titlekey (
  tk_page INTEGER UNSIGNED NOT NULL,
  tk_namespace INTEGER NOT NULL,
  tk_key BLOB NOT NULL,
  PRIMARY KEY(tk_page)
);

CREATE INDEX name_key ON /*_*/titlekey (tk_namespace, tk_key);
